server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
      timeout: 10000ms
      database: 0

  #profiles:
    #active: dev
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: pers.weisg.shiro.example.entity

#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

